{% set name = "table-evaluator" %}
{% set version = "1.6.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/table-evaluator-{{ version }}.tar.gz
  sha256: adcbb221e7ffd976aa0276264084be031edd647a84ff76d2c462ad1c8346593e

build:
  noarch: python
  script:
    - sed -i.bak 's/dython==0.7.3/dython/g' setup.py
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  build:
    - sed     # [unix]
    - m2-sed  # [win]
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - pandas ==2.0.*
    - numpy
    - tqdm
    - psutil
    - dython >=0.7.3,<0.8.0
    - seaborn
    - matplotlib-base
    - scikit-learn
    - scipy <=1.11.4

test:
  imports:
    - table_evaluator
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/Baukebrenninkmeijer/Table-Evaluator
  summary: A package to evaluate how close a synthetic data set is to real data.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - dillonroach
