{% set name = "table-evaluator" %}
{% set version = "1.7.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: a41ad25302b5a7bc131a28a0fa486c032a48fb5ff5ff8902584f10b96c357067

build:
  noarch: python
  script:
    - sed -i.bak 's/dython==0.7.3/dython/g' setup.py
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  build:
    - sed     # [unix]
    - m2-sed  # [win]
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - pandas ==2.0.*
    - numpy
    - tqdm
    - psutil
    - dython >=0.7.3,<0.8.0
    - seaborn
    - matplotlib-base
    - scikit-learn
    - scipy <=1.11.4

test:
  imports:
    - table_evaluator
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Baukebrenninkmeijer/Table-Evaluator
  summary: A package to evaluate how close a synthetic data set is to real data.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - dillonroach
